#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum PlayerAnimationState
{
	PLAYER_IDLE_L,
	PLAYER_IDLE_R,
	PLAYER_RUN_L,
	PLAYER_RUN_R,
	PLAYER_CLIMB,
	//PLAYER_JUMP_L,
	//PLAYER_JUMP_R,
	PLAYER_MELEE_L,
	PLAYER_MELEE_R,
	PLAYER_RANGE_L,
	PLAYER_RANGE_R,
	PLAYER_HURT_R,
	PLAYER_HURT_L,
	NUM_OF_PLAYER_ANIMATION_STATES
};

#endif /* defined (__PLAYER_ANIMATION_STATE__)*/